version: "3.9"

services:
  blog:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    restart: always
    env_file:
      - env.postgres
    expose:
      - 3000
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    env_file:
      - env.postgres
    expose:
      - 5432
    volumes:
      - /tmp/database:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
