version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    env_file:
      - dockerfiles/env.app
    depends_on:
      - database

  database:
    image: mysql:8.0.23
    expose:
      - 3306
    env_file:
      - dockerfiles/env.mysql
