version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    restart: always
    ports:
      - "80:8000"
    env_file:
      - dockerfiles/env.django
    depends_on:
      - database

  database:
    image: postgres:12-alpine
    restart: always
    volumes:
      - /tmp/postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - dockerfiles/env.postgres
