name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  DOCKER_USER   : longmama
  IMAGE_NAME    : front_app
  CONTAINER_NAME: front_app

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout to master
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to Docker Hub
      run: |
        docker build -t $DOCKER_USER/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) .
        docker push $DOCKER_USER/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)


  deploy:

    runs-on: ubuntu-latest
    needs: [build_and_push]

    steps:
    - name: Connect to server, pull and run app via docker
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: IMAGE_NAME, CONTAINER_NAME, GITHUB_SHA, DOCKER_USER
        script: |
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
          docker run -d \
          --restart always \
          --publish 80:80 \
          --name $CONTAINER_NAME \
          $DOCKER_USER/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)
